### ISSUE TITLE
Wouldn't work on Fedora 22

### ISSUE THREAD

**Issue by weldpua2008** [ANXS/build-essential#6]
Hi
You will get yum module not found here:
https://github.com/ANXS/build-essential/blob/master/tasks/main.yml#L15
Try with my docker image from https://hub.docker.com/r/weldpua2008/docker-ansible/tags/:

```
git clone https://github.com/ANXS/build-essential.git
cd build-essential
OS_TYPE=fedora 
OS_VERSION=22 
ANSIBLE_VERSION=1.9.2


sudo docker run --rm=true -v `pwd`:/build-essential:rw weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION} /bin/bash -c "
echo localhost > /build-essentia/inventory; ansible-playbook -i  /build-essentia/inventory  /build-essentia/test.yml --connection=local --sudo"

```

**Comment by otakup0pe** [comment]
What version of Ansible is this with? A PR would be welcome :)

**Comment by weldpua2008** [comment]
Ansible  1.9.2

**Comment by arhue** [comment]
@otakup0pe Since we are moving upto 2.3 as the min version courtesy of PR #14 , I guess you can close this.
